name: JavaScript Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  javascript-tests:
    name: Run JavaScript Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Latest Firefox
        run: |
          sudo apt-get purge -y firefox
          LATEST_VERSION=$(curl -s https://product-details.mozilla.org/1.0/firefox_versions.json | jq -r '.LATEST_FIREFOX_VERSION')
          echo "Latest Firefox version is $LATEST_VERSION"
          wget "https://ftp.mozilla.org/pub/firefox/releases/${LATEST_VERSION}/linux-x86_64/en-US/firefox-${LATEST_VERSION}.tar.xz" -O firefox.tar.xz
          tar -xJf firefox.tar.xz
          sudo mv firefox /opt/firefox
          sudo ln -sf /opt/firefox/firefox /usr/bin/firefox

      - name: Install Required System Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-glib-1-2 libgtk-3-0 xvfb

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: xvfb-run --auto-servernum npm run test || echo "⚠️ Tests skipped — no workspaces available"
